# Generated by Django 4.0.3 on 2022-05-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='user',
            field=models.ForeignKey(default=uuid.uuid1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
